name: Analyzing headlines with spaCy
description: Demonstrating Named Entity Recognition and some downstream analysis on a Reuters news dataset.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-04-05"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.9
    edition: Standard
